apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blazar.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  blazar.conf: |
{{ include "blazar-conf" . | indent 4 }}
