apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "blazar.fullname" . }}-db-sync
  labels:
    {{- include "blazar.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
        {{- include "blazar.vaultAnnotations" . | nindent 8 }}
      labels:
        {{- include "blazar.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "blazar.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.manager.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - blazar-db-manage
            - --config-file
            - /etc/blazar/blazar.conf
            - --config-file
            - /etc/blazar/blazar.conf.d/secrets.conf
            - upgrade
            - head
          volumeMounts:
            - name: {{ include "blazar.fullname" . }}
              mountPath: "/etc/blazar/"
      volumes:
        - name: {{ include "blazar.fullname" . }}
          configMap:
            name: {{ include "blazar.fullname" . }}
